### PR TITLE
Create README

### LINKED ISSUE #16: Create README

### PR DESCRIPTION
**Pull request by mic-css**
Created a README at root level detailing build, run and test steps.
Closes #16

### CODE REVIEW

**Comment by Itsindigo** [comment]
:shipit:

**Comment by tishayaem** [comment]
:shipit:

**Comment by tishayaem** [comment]
Good job MIc

**Comment by mic-css** [comment]
Waiting for Jeremy to push up db instructions, DON'T SHIP YET

**Pull request merged**
