### PR TITLE
6 mongo db setup

### LINKED ISSUE #6: MongoDB setup
Install and build

### PR DESCRIPTION
**Pull request by Jeremy-Barrass**
I believe we have everything we need for database set up and user model.  We still don't have user authentication running, but that can be done via passport, so I have skipped it.
closes #6

### CODE REVIEW

**Comment by Itsindigo** [comment]
:shipit:

**Comment by mic-css** [comment]
Waiting for Jeremy's db build instructions before squirreling

**Comment by mic-css** [comment]
Make sure to pull from dev and fix conflicts, then :shipit: !

**Comment by Jeremy-Barrass** [comment]
That should all be ready now.  Anymore squirrels before merging?

**Comment by mic-css** [comment]
:shipit: squirrelz all round

**Pull request merged**
